# example netlify.toml
[build]
command = "astro build"
functions = "netlify/functions"
publish = "dist"

[[plugins]]
package = "netlify-plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"